/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.atividade07.view;

import br.com.ifba.atividade07.logic.Pagamento;
import br.com.ifba.atividade07.logic.PagamentoCartao;
import br.com.ifba.atividade07.logic.PagamentoDinheiro;
import br.com.ifba.atividade07.logic.PagamentoPix;
import javax.swing.JOptionPane;

/**
 *
 * @author Jacks
 */
public class InterfacePagamento extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(InterfacePagamento.class.getName());

    /**
     * Creates new form InterfacePagamento
     */
    public InterfacePagamento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cboPaymentOption = new javax.swing.JComboBox<>();
        lblTitle = new javax.swing.JLabel();
        lblInformText = new javax.swing.JLabel();
        btnConfirm = new javax.swing.JButton();
        lblReceipt = new javax.swing.JLabel();
        lblInsertValue = new javax.swing.JLabel();
        txtValue = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cboPaymentOption.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cboPaymentOption.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cartão de crédito", "Dinheiro", "Pix" }));
        cboPaymentOption.addActionListener(this::cboPaymentOptionActionPerformed);

        lblTitle.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTitle.setText("Bem vindo(a) a loja swing");

        lblInformText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblInformText.setText("Selecione um método de pagamento");

        btnConfirm.setText("Confirmar");
        btnConfirm.addActionListener(this::btnConfirmActionPerformed);

        lblReceipt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblReceipt.setToolTipText("");

        lblInsertValue.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblInsertValue.setText("Insira o valor da compra");

        txtValue.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblTitle)
                        .addGap(118, 118, 118))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnConfirm)
                        .addGap(175, 175, 175))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblInsertValue)
                                .addGap(26, 26, 26)
                                .addComponent(txtValue, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblInformText)
                                .addGap(18, 18, 18)
                                .addComponent(cboPaymentOption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(lblReceipt)))
                .addGap(0, 32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInsertValue)
                    .addComponent(txtValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInformText)
                    .addComponent(cboPaymentOption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(btnConfirm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(lblReceipt)
                .addGap(86, 86, 86))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboPaymentOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboPaymentOptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboPaymentOptionActionPerformed

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
        try{
            double valor = Double.parseDouble(txtValue.getText());
            String tipoPagamento = cboPaymentOption.getSelectedItem().toString();
            Pagamento pagamento = null;
            // Atribuindo ausencia proposital de valor para utilizar depois
            
            if (tipoPagamento.equals("Pix")) {
                pagamento = new PagamentoPix(valor);
            } else if (tipoPagamento.equals("Dinheiro")) {
                pagamento = new PagamentoDinheiro(valor);
            } else {
                pagamento = new PagamentoCartao(valor);
            }
            
            lblReceipt.setText(pagamento.imprimirRecibo());
        }
        catch(NumberFormatException e) {
            JOptionPane.showMessageDialog(null,"Erro ao converter string para número!\n"  
                    + "Certifique-se de digitar um número no campo de inserir valor.\n" + e);
        }
    }//GEN-LAST:event_btnConfirmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new InterfacePagamento().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirm;
    private javax.swing.JComboBox<String> cboPaymentOption;
    private javax.swing.JLabel lblInformText;
    private javax.swing.JLabel lblInsertValue;
    private javax.swing.JLabel lblReceipt;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtValue;
    // End of variables declaration//GEN-END:variables
}
