/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.atividade03.view;
import br.com.ifba.atividade03.logic.AgeCalculator;
/**
 *
 * @author Jacks
 */
public class InterfaceCalculator extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(InterfaceCalculator.class.getName());

    /**
     * Creates new form InterfaceCalculator
     */
    public InterfaceCalculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblGreetings = new javax.swing.JLabel();
        lblAskYear = new javax.swing.JLabel();
        btnSubmitYear = new javax.swing.JButton();
        lblResult = new javax.swing.JLabel();
        spnYearField = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblGreetings.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblGreetings.setText("Bem vindo(a) a calculadora de idade");

        lblAskYear.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblAskYear.setText("Informe o seu ano de nascimento:");

        btnSubmitYear.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSubmitYear.setIcon(new javax.swing.ImageIcon("C:\\Users\\Jacks\\Pictures\\imgForProjects\\calculator.jpg")); // NOI18N
        btnSubmitYear.setText("Confirmar");
        btnSubmitYear.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnSubmitYear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSubmitYear.addActionListener(this::btnSubmitYearActionPerformed);

        lblResult.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        spnYearField.setModel(new javax.swing.SpinnerNumberModel(2000, 1940, 2026, 1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(144, Short.MAX_VALUE)
                .addComponent(lblGreetings)
                .addGap(39, 39, 39))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSubmitYear)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(27, 27, 27)
                            .addComponent(lblResult))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(15, 15, 15)
                            .addComponent(lblAskYear)
                            .addGap(18, 18, 18)
                            .addComponent(spnYearField, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblGreetings)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAskYear)
                    .addComponent(spnYearField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addComponent(btnSubmitYear)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                .addComponent(lblResult)
                .addGap(99, 99, 99))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitYearActionPerformed
        // TODO add your handling code here:
        
        int birthYear = (int) spnYearField.getValue();
            
        int age = AgeCalculator.calculateAge(birthYear);
            
        lblResult.setText("Sua idade é de -> " + age + " Anos");
        
        
    }//GEN-LAST:event_btnSubmitYearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new InterfaceCalculator().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmitYear;
    private javax.swing.JLabel lblAskYear;
    private javax.swing.JLabel lblGreetings;
    private javax.swing.JLabel lblResult;
    private javax.swing.JSpinner spnYearField;
    // End of variables declaration//GEN-END:variables
}
